# Generated by Django 5.0.3 on 2024-04-02 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
